# Site settings
title: SEI 19
email: sei@cesium.di.uminho.pt
year: 2019
short_year: 19
prev_year: 2018
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seium.org" # the base hostname & protocol for your site
facebook: SEI.UMinho
twitter: cesiuminho
github: cesium
website: http://cesium.di.uminho.pt

highlighter: rouge

# Build settings
markdown: kramdown

plugins:
- jekyll-assets
- jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["pt", "en"]
