# Site settings
title: SEI 19
email: sei@cesium.di.uminho.pt
year: 2019
short_year: 19
prev_year: 2018
description: > 
  SEI - Semana da Engenharia Informática, uma semana organizada por alunos e
  para alunos, gratuita e totalmente dedicada a apresentar e aprofundar temas
  de destaque no panorama atual da informática. Anteriormente chamada Semana
  da LEI, a SEI ocobrre no Departamento de Informática da UMinho. Este ano
  apresenta uma Hackathon, várias palestras e workshops orientados por
  oradores de relevo nacional e internacional, momentos de discussão,
  pró-atividade e de lazer bem como uma abordagem social.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seium.org" # the base hostname & protocol for your site
facebook: SEI.UMinho
twitter: cesiuminho
github: cesium
website: http://cesium.di.uminho.pt

highlighter: rouge

# Build settings
markdown: kramdown

plugins:
- jekyll-assets
- jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["pt", "en"]
